EGG_NAMES = ["Spotted",
"Fire Comb",
            "Water Comb",
            "Lightning Comb",
            "Ice Comb",
            "Wind Comb",
            "Iron Comb",
            "Light Comb",
            "Wings",
            "Booster",
            "Paraloop",
            "Thorn Egg",
            "Speed Shoes",
            "Bomb",
            "Spring Shoes",
            "Circus Hat",
            "Psychic Hat",
            "Heart Hat",
            "Bat",
            "Crow",
            "Cipher",
            "Clippen",
            "Recky",
            "Richie",
            "Peliwan",
            "Runny",
            "Rabbish",
            "Rikol",
            "Kaboot",
            "Datch",
            "Glarin",
            "Baskus",
            "Oritta",
            "Biboo",
            "Gorilla",
            "Chameleon",
            "Mouse",
            "Turtle",
            "Lion",
            "Dice",
            "Super Fruit",
            "Tiger",
            "Sheep",
            "Hawk",
            "Fox",
            "Large Butterfly",
            "Stopwatch",
            "Small Butterfly",
            "1 Up",
            "Chick Bomb",
            "Egg Bomb",
            "Game Boy Advance Game: Chu Chu Rocket Challenge",
            "Game Boy Advance Game: Nights Score Attack",
            "Game Boy Advance Game: Billy Hatcher Shoot - Easy",
            "Game Boy Advance Game: Billy Hatcher Hyper Shoot",
            "Game Boy Advance Game: Puyo Pop",
            "Sonic",
            "Tails",
            "Knuckles",
            "Chao",
            "Rappy",
            "Kapu Kapu",
            "NIGHTS",
            "Amigo",
            "Super Clippen",
            "Super Recky",
            "Chicken Suit",
            "Oma-Oma",
            "Uri-Uri",
            "Ura-Ura",
            "Ponee",
            "Allani",
            "Mera-Mera"
]

EXCLUDE_EGGS = ["Chicken Suit",
            "Oma-Oma",
            "Uri-Uri",
            "Ura-Ura",
            "Ponee",
            "Allani",
            "Mera-Mera",
                "NIGHTS",
                "Knuckles",
                "Richie",
                "Cipher",
                "Recky",
                "Spotted"]
WORLD_NAMES = [
    "Forest",
    "Pirate",
    "Dino",
    "Blizzard",
    "Circus",
    "Sand",
    "Palace",
]
SHORT_EXCLUDE_WORLDS = ["Palace"]
FRIEND_NAMES = [
    "Rolly",
    "Chick",
    "Bantam"
]